baseURL: "https://mynewhugosite.com"
title: "My Hugo Site"
theme: "hugo-theme-kaleidoscope"

params:
  mainSections: ['posts']
  author: "Bravishka Skytano"
  favicon: ""
  site_logo: ""
  description: "The most colorful Hugo theme you will ever find."
  featured_posts: true
  
  # choose fonts from
  main_font: ""
  title_font: ""
  header_font: ""
  
  # choose colors from https://tachyons.io/docs/themes/skins/
  main_bg_color: ""
  text_color: ""
  card_bg_color: ""
  link_color: ""
  button_color: ""
  button_text_color: ""
  # Lower the color brightness by percentage for darkmode
  dm_brightness: ""

menu:
  main:
  -
    name: "Home"
    url: "/"
    weight: 1
  -
    name: "About"
    url: "/about"
    weight: 2
  -
    name: "Posts"
    url: "/posts"
    weight: 3
  -
    name: "Categories"
    url: "/categories"
    weight: 4
  -
    name: "Tags"
    url: "/tags"
    weight: 5

enableGitInfo: true
frontmatter:
  date: ["date", "publishDate", "lastmod"]
  lastmod: ["lastmod", ":git", "date", "publishDate"]

related:
  includeNewer: true
  threshold: 0
  toLower: false
  indices:
    -
      name: 'categories'
      weight: 100
    -
      name: 'tags'
      weight: 50
    -
      name: 'date'
      weight: 10
