baseURL: "https://mynewhugosite.com"
title: "My Hugo Site"
theme: "kaleidoscope"

params:
  mainSections: ['posts']
  author: "Bravishka Skytano"
  favicon: ""
  site_logo: ""
  description: "The most colorful Hugo theme you will ever find."
  featured_posts: true
  #fontawesome: 
  
  # View fonts on http://tachyons.io/docs/typography/font-family/
  # Options: sans-serif, serif, system-sans-serif, code, courier, helvitica,
  # avenir, athelas, georgia, times, bodoni, calisto, garamond, baskerville
  main_font: "avenir"
  title_font: "georgia"
  header_font: "baskerville"

# https://gohugo.io/content-management/menus/
menu:
  main:
  - 
    name: About
    pageRef: /about
    weight: 10
  - 
    name: Posts
    pageRef: /posts
    weight: 20
  - 
    name: Categories
    pageRef: /categories
    weight: 30
  - 
    name: Tags
    pageRef: /tags
    weight: 40

  footer: # fonts are from FontAwesome
  - 
    name: Github
    params:
      rel: external
    pre: <i class="fa-brands fa-github"></i>
    url: https://github.com/BravishkaSkytano
    weight: 30

# lastmod
enableGitInfo: true
frontmatter:
  date: ["date", "publishDate", "lastmod"]
  lastmod: ["lastmod", ":git", "date", "publishDate"]

related:
  includeNewer: true
  threshold: 0
  toLower: false
  indices:
    -
      name: 'categories'
      weight: 100
    -
      name: 'tags'
      weight: 50
    -
      name: 'date'
      weight: 10
