baseURL: "https://mynewhugosite.com"
title: "My Hugo Site"
theme: "kaleidoscope"

params:
  mainSections: ['posts']
  author: "Bravishka Skytano"
  favicon: ""
  site_logo: ""
  description: "The most colorful Hugo theme you will ever find."
  featured_posts: true
  
  # View fonts on http://tachyons.io/docs/typography/font-family/
  # Options: sans-serif, serif, system-sans-serif, code, courier, helvitica,
  # avenir, athelas, georgia, times, bodoni, calisto, garamond, baskerville
  main_font: "avenir"
  title_font: "georgia"
  header_font: "baskerville"

menu:
  main:
  -
    name: "About"
    url: "/about"
    weight: 1
  -
    name: "Posts"
    url: "/posts"
    weight: 2
  -
    name: "Categories"
    url: "/categories"
    weight: 3
  -
    name: "Tags"
    url: "/tags"
    weight: 4

# lastmod
enableGitInfo: true
  date: ["date", "publishDate", "lastmod"]
  lastmod: ["lastmod", ":git", "date", "publishDate"]

related:
  includeNewer: true
  threshold: 0
  toLower: false
  indices:
    -
      name: 'categories'
      weight: 100
    -
      name: 'tags'
      weight: 50
    -
      name: 'date'
      weight: 10
